<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>0.0.1</Version>
    <ApplicationIcon>Assets\midi-connector.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\WECPBXR.Console\midi-map.json" Link="midi-map.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <ProjectReference Include="..\WECPBXR.Core\WECPBXR.Core.csproj" />
    <ProjectReference Include="..\WECPBXR.Hardware\WECPBXR.Hardware.csproj" />
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
